### ISSUE TITLE
Add possibility to generate duplicate entries on signature sheets

### ISSUE THREAD

**Issue by benjaminpreiss** [spschweiz/demovox#13]
## Description

A client of mine (**umverkehr.ch**) requested me to adjust the demovox plugin to allow duplicate fields on a signature sheet.

Specifically I will make the following adjustments:

### Add duplication mechanism for signature sheet field positions:

- Leverage `fieldCallback($arguments)` to create **+** and **-** buttons ([link to code](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/admin/AdminSettings.php#L194))
- Use javascript to capture `onClick` events and add signature fields during runtime
- Limit **-** `onClick` actions to avoid having no field to specify positions at all.
- Autogenerate indexed position input / form element names to add php `$_REQUEST` ability

![signature_sheet_fields_duplication_mechanism](https://user-images.githubusercontent.com/28349122/90037849-f3c9a280-dcc4-11ea-89a5-213fda10afaf.png)

### Output duplicate fields to signature sheet

- Edit `$fields` in `step3inlineSuccessPage` to accommodate duplicate fields ([link to code](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/public/SignSteps.php#L295)):
```php
		$fields = [
			'field_canton'          => strtoupper($gdeCanton),
			'field_canton_1'          => strtoupper($gdeCanton),
			'field_commune'         => $gdeName,
                        // etc
		];
```
- Make sure that `Config::getValueByUserLang` in `formatFields` gets passed the correct `$name` ([link to code](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/public/SignSteps.php#L410-L412))

## Notes

Ideas and comments on the implementation are very welcome.
I will commit a pull request in the end containing my implementation.

**Comment by Horlacher** [comment]
Hello Benjamin

I'm very happy you're here to advance demovox.

You have to think about where to store those additional values.

At the moment, each each _pos_rot_ is stored in [three predefined wordpress settings](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/admin/AdminSettings.php#L181-L183).
```php
register_setting($page, $id . Config::GLUE_PART . Config::PART_POS_X, $argX);
register_setting($page, $id . Config::GLUE_PART . Config::PART_POS_Y, $argY);
register_setting($page, $id . Config::GLUE_PART . Config::PART_ROTATION, $argRot);
```

I think it would be best to replace those three wordpress settings with a single one in a JSON array `json_encode()` which would allow you to dynamically add more fields into it. The content of such a setting (in your case the definition of canton) could look like this: 
```json
[{"x":100,"y":655,"rot":90},{"x":150,"y":300,"rot":270}]
```
When reading the settings [here in AdminSettings](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/admin/AdminSettings.php#L253-L255) and [here in SignSteps](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/public/SignSteps.php#L410-L412), replace it with something like this  and then loop through the values:
```php
$coordFields = json_decode(Config::getValue($uid));
foreach ($coordFields as $field) {
	$posX = $field['x']
	// ...
}
```

Replacing those settings would also require you to take care of those parts as well: [deleteAll()](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/includes/helpers/Config.php#L81-L83) and [initDefaults()](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/includes/helpers/Config.php#L113-L121).
And don't forget to create a migration of the old values in the [Activator](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/includes/wp/Activator.php).

I'm looking forward to your pull request.

Greetings
Fabian

**Comment by benjaminpreiss** [comment]
@Horlacher Thanks very much for the advice! I guess I am halfway through already...
The idea with the hidden field is working out so far as well.
There is one thing that I am curious about: I am getting a strange error during `grunt buildAssets`:
```bash
Running "po2mo:files" (po2mo) task
Warning: Can not create sync-exec directory Used --force, continuing.
```
Do you know what that is about?

**Comment by benjaminpreiss** [comment]
Also I intend to register the `onChange` javascript functions globally in [demovox-admin.js](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/admin/js/demovox-admin.js#L2):

```js
window.newFunction = function(string) {
    console.log('example');
}
```

Then I can directly supply the function as `onchange` attribute during `<input>` generation in [AdminSettings.php](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/admin/AdminSettings.php#L257).

Any objections?

**Comment by Horlacher** [comment]
> ```shell
> Running "po2mo:files" (po2mo) task
> Warning: Can not create sync-exec directory Used --force, continuing.
> ```


This is a [known issue of po2mo](https://github.com/MicheleBertoli/grunt-po2mo/issues/8) with the current node.js version and that's why I'm still using node.js v8.x. po2mo is the [recommended localisation generator of wordpress](https://developer.wordpress.org/plugins/internationalization/localization/#grunt-task) for grunt, but it would be great to replace the plugin with a better solution.

**Comment by benjaminpreiss** [comment]
### Status quo

Okey, so I am done with the first step:

1. Add position field duplication mechanism in demovox admin area
2. Make created fields saveable.

Here is the [commit](https://github.com/benjaminpreiss/demovox/commit/a588aea61c9bc28fe1a55de6fe6022758da1ea5b) and the [branch](https://github.com/benjaminpreiss/demovox/tree/umverkehr) with the new code.

### Help needed

1. The front end side of the demovox _Signature sheet_ area **works as expected** now.
2. There is some strange behaviour though in the database that I **need some help** with. The hidden json field values are not properly stored to the database:
    - When emptying all db entries in `wp_options` starting with `demovox_field_` and then reloading the admin page no json field values are stored in the db. Only the `..._x`, `..._y`, `..._rot` values are stored:
![image](https://user-images.githubusercontent.com/28349122/90754817-aeb3fa80-e2da-11ea-84a7-6aeb6e6c8c5c.png)

    - When pressing the _Save Changes_ button also no json field values are stored.
![image](https://user-images.githubusercontent.com/28349122/90754905-cbe8c900-e2da-11ea-8d00-7637961172b3.png)

    - When pressing the + or - button only the corresponding json field values are stored (in this case canton):
![image](https://user-images.githubusercontent.com/28349122/90755099-12d6be80-e2db-11ea-84c2-4386caaa3d73.png)

Do you have an idea why that is? Did I register the json setting in the wrong way? Or is it the missing activator entry?

**Comment by benjaminpreiss** [comment]
Just fyi - I created a [project](https://github.com/benjaminpreiss/demovox/projects/1) containing all the remaining to do's!

**Comment by Horlacher** [comment]
Example on how to create the browser functionality (while reading and generating the JSON on the client)
https://jsfiddle.net/Horlacher/95bq4gjd/23/

```html
<table>
<tr>
<td class="demovox_field_row">

<div class="demovox_field_group">
<!-- similar to the old code, but with class instead of field-specific name & ID -->
<input class="demovox_field_x" type="number" placeholder="x" size="5">
<input class="demovox_field_y" type="number" placeholder="y" size="5">
<select class="demovox_field_rot">
<option value="0">Normal orientation</option><option value="90">Rotate 90° clockwise</option><option value="180">Rotate 180°</option><option value="270">Rotate 90° counter-clockwise</option>
</select>
</div>
hidden field:
<input class="demovox_field" type="text" name="{$the_wordpress_field_id}" id="{$the_wordpress_field_id}" value='[{"x":100,"y":655,"rot":90},{"x":150,"y":300,"rot":270}]'>

<p class="description">Position on the sign sheet "x-y" while y is measured from bottom to top</p>
<button type="button" class="demovox_field_group_add">+</button><button type="button" class="demovox_field_group_remove">-</button>
</td>
</tr>
</table>
```
JavaScript:
```javascript
$("td.demovox_field_row").each(function(index) {
	var $row = $(this),
		$field =  $row.find('.demovox_field'),
		jsonString = $field.val(),
		$group = $row.find('.demovox_field_group');
	if (jsonString) {
		json = JSON.parse(jsonString);
		$.each(json, function(key, value) {
			createGroup($row, $group, value.x, value.y, value.rot);
		});
    $group.hide();
	}
  
	$(this).find('.demovox_field_group_add').on('click', function() {
		createGroup($row, $group);
	});
	$(this).find('.demovox_field_group_remove').on('click', function() {
		$row.find('.demovox_field_group:last').remove();
		genJson($row, $field);
	});
	$(this).on('change', '.demovox_field_group input, .demovox_field_group select', function() {
		genJson($row, $field);
	});
});
function createGroup($row, $group, x, y, rot){
	var $lastGroup = $row.find('.demovox_field_group:last')
		$created = $group.clone().insertAfter($lastGroup);
  if (typeof x !== 'undefined') {
    $created.find('.demovox_field_x').val(x);
    $created.find('.demovox_field_y').val(y);
    $created.find('.demovox_field_rot').val(rot);
  }
  $created.show();
}
function genJson($row, $field) {
	var values = [];
	$row.find('.demovox_field_group').each(function(index) {
		var $group = $(this),
    	x = $group.find('.demovox_field_x').val(),
      y = $group.find('.demovox_field_y').val(),
      rot = $group.find('.demovox_field_rot').val();
    if(x == '' || y == '' || rot == '') { return; }
		values.push({x: Number(x), y: Number(y), rot: Number(rot)});    
	});
	$field.val(JSON.stringify(values));
}
```

**Comment by benjaminpreiss** [comment]
Ah, sure! Would you prefer to have it implemented it like that?

**Comment by Horlacher** [comment]
I think it's the simplest approach to implement it

**Comment by benjaminpreiss** [comment]
Sure! Did you have a change to think about the json variables not fully being saved to the db?

**Comment by benjaminpreiss** [comment]
A new [commit](https://github.com/benjaminpreiss/demovox/commit/739ecf0517c40715743fd2a6a7c57f48677aecf5) reflecting all discussed changes, except the client side json generation. Also I cleaned up the code. The above mentioned db problem still persists.

Client side json generation commit will follow soon.

**Comment by Horlacher** [comment]
> The above mentioned db problem still persists

I think it's your JavaScript which doesn't always generate the JSON when needed and the hidden input field stays empty prior to saving. Check the value of the hidden field and simplify your script (or just take mine).

> A new [commit](https://github.com/benjaminpreiss/demovox/commit/739ecf0517c40715743fd2a6a7c57f48677aecf5) reflecting all discussed changes

You can remove `const PART_ROTATION, PART_POS_X, PART_POS_Y` everywhere, there is no need for them anymore when everything is stored in the JSON field anyway. `PART_POS_JSON` is not needed either, as there is no more variations for this setting. Just use `$id` instead of `$id . Config::GLUE_PART . Config::PART_POS_JSON`

Be aware if you use my JavaScript proposition, you don't need to loop through the JSON on the server in [AdminSettings](https://github.com/benjaminpreiss/demovox/blob/739ecf0517c40715743fd2a6a7c57f48677aecf5/admin/AdminSettings.php#L268). Just provide a template for the positioning fields and the json input (`<div class="demovox_field_group">...</div>` and `<input class="demovox_field"...>` in example above)

**Comment by benjaminpreiss** [comment]
Finally. I think all is done (except Activator adjustments). I would be very happy to receive your feedback!

Here is the last [commit](https://github.com/benjaminpreiss/demovox/commit/8013403daa606f2d7dd08cac2b6640bdc8e7a6f3)

**Comment by benjaminpreiss** [comment]
okey, so there was still a little error. New [commit](https://github.com/benjaminpreiss/demovox/commit/f1946edd5b85ff0d8d888972cc45ef0b963601d8).

I just tested the plugin. Works as expected. But there is an issue with the optin-page. Somehow the optin shortcode does not work:

![image](https://user-images.githubusercontent.com/28349122/91340537-77f94b00-e7d8-11ea-814b-9b244923aeb4.png)

With debugging enabled I found the issue to be in [PublicHandler.php](https://github.com/benjaminpreiss/demovox/blob/f1946edd5b85ff0d8d888972cc45ef0b963601d8/public/PublicHandler.php#L89). Seems that `$REQUEST` has no `'sign'` key. Can you help me with that?

**Comment by Horlacher** [comment]
> Seems that `$REQUEST` has no `'sign'`

That's right, you need to pass the `guid` of the signature you want to edit the optin info. You can find the value in `demovox_signatures.guid`
The signee will receive the correct URL by mail, if link_optin is used in the mail.

**Comment by Horlacher** [comment]
> Also it is not quite clear to me what has to be changed in Activator?

Read the old config for the affected fields (formerly `PART_ROTATION`, `PART_POS_X` and `PART_POS_Y`), generate and store the new JSON value instead and then delete the old fields.

**Comment by benjaminpreiss** [comment]
Hey, ja klar :) Ich dachte es wäre für die Nachwelt leichter nachzuvollziehen, wenn wir auf Englisch kommunizieren :)

> > Seems that `$REQUEST` has no `'sign'`
> 
> That's right, you need to pass the `guid` of the signature you want to edit the optin info. You can find the value in `demovox_signatures.guid`. Example URL: http://localhost/optinpage?sign=yourguid
> The signee will receive the correct URL by mail, if `link_optin` is used in the mail.

Ich kann dir leider noch nicht ganz folgen :/ Gibt es eine Einstellung in der Benutzeroberfläche, die ich entsprechend verändern kann? Oder muss ich in den Code rein?

**Comment by benjaminpreiss** [comment]
Okey, new [commit](https://github.com/benjaminpreiss/demovox/commit/3514fd18c5f33cd516c9ed86fcb9684ab223355b) with all the requested cosmetic and style changes.

**Comment by benjaminpreiss** [comment]
Could you maybe help me with the activator?
