### ISSUE TITLE
Change namespace of PHPMailer

### ISSUE THREAD

**Issue by benjaminpreiss** [spschweiz/demovox#15]
As of WordPress v5.5 `\PHPMailer` has another namespace `\PHPMailer\PHPMailer\PHPMailer`.

[https://wordpress.org/support/topic/phpmailer-error-2/](https://wordpress.org/support/topic/phpmailer-error-2/).

There are two lines that could be changed to solve this problem in `Mail.php`:

1. [https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/includes/helpers/Mail.php#L80](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/includes/helpers/Mail.php#L80)
2. [https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/includes/helpers/Mail.php#L42](https://github.com/spschweiz/demovox/blob/20c357bb58a1273ba5f3f7f0ceacfae55c7747c1/includes/helpers/Mail.php#L42)

**Comment by Horlacher** [comment]
Thanks for the fix! can you send a pull request for those changes?

**Comment by benjaminpreiss** [comment]
There you go!
